title: "Osas Familia"
email: osas.sob@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo_osas.png'
favicon: 'assets/images/favicon.ico'
author: Osas Dev
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  sal:
    name: Osas Dev
    display_name: Osas Dev
    avatar: 'assets/images/sal.png'
    email: osas.sob@gmail.com
    web: 
    twitter: 
    description: "Osas Familia Pernah Disini"


# Social
social:
  instagram: https://www.instagram.com/osas.sob/


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives